language: c

services:
  - docker

os:
  - linux
  - osx

env:
  - CONF: werror
  - CONF: goffice

before_install:
    # Linux: create Docker image
    - export DIST_NAME=debian DIST_VERS=testing TAG=grisbi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ${DIST_NAME}:${DIST_VERS} ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build --rm=true --file=travis-ci/Dockerfile.${DIST_NAME}-${DIST_VERS} --tag=${DIST_NAME}-${DIST_VERS}:${TAG} travis-ci ; fi

    # macOS: install packages
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf libtool intltool goffice gtk+3 libgsf libofx ; fi

script:
    - echo "export TRAVIS_OS_NAME=$TRAVIS_OS_NAME" > travis-ci/env
    - echo "export CONF=$CONF" >> travis-ci/env

    # Command to execute
    - CMD=". travis-ci/env ; ./travis-ci/travis-autogen.sh ; make"

    # Linux
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --volume=`pwd`:/build ${DIST_NAME}-${DIST_VERS}:${TAG}
      /bin/sh -c "$CMD" ; fi
    # macOS
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      /bin/sh -c "$CMD" ; fi
